// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP BayesIV_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
// ThetaUpdateNormal_DPM
NumericVector ThetaUpdateNormal_DPM(NumericVector Yobs, NumericVector XX, NumericVector XTr, NumericVector Z, NumericVector Tr, NumericVector Trstar, NumericVector Theta, NumericVector sigmaSq, NumericVector muY, NumericVector Beta1, double Alpha1, NumericVector Beta0, double Alpha0, double AlphaD, double Gamma, NumericVector BetaT, int n, int pp, double mu, NumericVector tau);
RcppExport SEXP BayesIV_ThetaUpdateNormal_DPM(SEXP YobsSEXP, SEXP XXSEXP, SEXP XTrSEXP, SEXP ZSEXP, SEXP TrSEXP, SEXP TrstarSEXP, SEXP ThetaSEXP, SEXP sigmaSqSEXP, SEXP muYSEXP, SEXP Beta1SEXP, SEXP Alpha1SEXP, SEXP Beta0SEXP, SEXP Alpha0SEXP, SEXP AlphaDSEXP, SEXP GammaSEXP, SEXP BetaTSEXP, SEXP nSEXP, SEXP ppSEXP, SEXP muSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type Yobs(YobsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type XTr(XTrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tr(TrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Trstar(TrstarSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigmaSq(sigmaSqSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type muY(muYSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Beta1(Beta1SEXP);
    Rcpp::traits::input_parameter< double >::type Alpha1(Alpha1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Beta0(Beta0SEXP);
    Rcpp::traits::input_parameter< double >::type Alpha0(Alpha0SEXP);
    Rcpp::traits::input_parameter< double >::type AlphaD(AlphaDSEXP);
    Rcpp::traits::input_parameter< double >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type BetaT(BetaTSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    __result = Rcpp::wrap(ThetaUpdateNormal_DPM(Yobs, XX, XTr, Z, Tr, Trstar, Theta, sigmaSq, muY, Beta1, Alpha1, Beta0, Alpha0, AlphaD, Gamma, BetaT, n, pp, mu, tau));
    return __result;
END_RCPP
}
