# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('BayesIV_rcpp_hello_world', PACKAGE = 'BayesIV')
}

ThetaUpdateNormal_DPM <- function(Yobs, XX, XTr, Z, Tr, Trstar, Theta, sigmaSq, muY, Beta1, Alpha1, Beta0, Alpha0, AlphaD, Gamma, BetaT, n, pp, mu, tau) {
    .Call('BayesIV_ThetaUpdateNormal_DPM', PACKAGE = 'BayesIV', Yobs, XX, XTr, Z, Tr, Trstar, Theta, sigmaSq, muY, Beta1, Alpha1, Beta0, Alpha0, AlphaD, Gamma, BetaT, n, pp, mu, tau)
}

